### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by james-luther** [CemitDigital/trivy-report-issue-action#1]
When this action runs on some of my repos when the Trivy scan is ran in 'fs' mode I receive this error when parsing the results.json

![image](https://user-images.githubusercontent.com/81767471/166970600-470fb690-1541-4920-b9bb-5cbfec044483.png)

Here is my action:

```
# This workflow performs Static Code Analysis checks

name: Static Code Analysis

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          hide-progress: false
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          format: 'json'
          output: 'result.json'
      
      - uses: CemitDigital/trivy-report-issue-action@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          input-filename: "result.json"
          label: 'vulnerability'
          assignee: ''
          project-id: ''
```

This works fine on most repositories but I've found on ones that it finds nothing this error occurs. I want to run this even when it finds no files to scan because it looks for secrets that could potentially be in the repo.

https://aquasecurity.github.io/trivy/v0.27.1/docs/secret/scanning/
